# Generated by Django 5.1.4 on 2025-01-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_college_formdata_alter_formdata_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formdata',
        ),
    ]
