# Generated by Django 5.1.4 on 2025-01-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_formdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='college',
            field=models.CharField(default='blank college', max_length=100),
        ),
    ]
