# Generated by Django 5.1.4 on 2025-01-19 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_formdata_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.college_formdata'),
        ),
    ]
